<!--[if (lt IE 9) & (!IEMobile)]>
<script type="text/javascript" src="js/lib/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="js/lib/jquery.min.js"></script>
<script type="text/javascript" src="js/lib/combobox.js"></script>
<script type="text/javascript" src="js/lib/jquery.myGallery.js"></script>
<script type="text/javascript" src="js/lib/jquery.flexslider-min.js"></script>
<script type="text/javascript" src="js/js.js"></script>