<?php
/**
 * @file Wc ShushiNeko custom functionality
 */

define('WCMUSASHIS_EMAIL_US_WEBFORM_NID', 13);
define('WCMUSASHIS_CONTACT_US_NID', 12);
define('WCMUSASHIS_NEWSLETTER_WEBFORM_NID', 2);

/**
 * Implements hook_menu().
 */
function wcmusashis_custom_menu() {
  $items['admin/wcmusashis/config'] = array(
    'title' => 'Musashi\'s Configuration',
    'description' => 'Musashi\'s Configuration page',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wcmusashis_custom_site_setings_form'),
    'access arguments' => array('custom site settings form access'),
    'file' => 'wcmusashis_custom.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function wcmusashis_custom_permission() {
  return array(
    'custom site settings form access' => array(
      'title' => t('Site configuration form access'),
      'description' => t('Access to Site configuration form with site information like: social links, company information in footer block etc.')
    ),
    'menu access admin index item' => array(
      'title' => t('Display "Index" item in admin menu.'),
      'description' => t('Display "Index" item in admin menu.')
    ),
  );
}


/**
 * Implements hook_preprocess_page().
 */
function wcmusashis_custom_preprocess_page(&$vars) {
  $node_type = (isset($vars['node']->type)) ? $vars['node']->type : NULL;

  if (in_array('page__node__edit', $vars['theme_hook_suggestions'])) {
    switch ($node_type) {
      case "homepage":
        drupal_set_title(t("Edit Homepage"));
        break;
      case "about_us":
        drupal_set_title(t("Edit About Us"));
        break;
      case "careers":
        drupal_set_title(t("Edit Careers"));
        break;
      case "gallery":
        drupal_set_title(t("Edit Gallery"));
        break;
      case "contact_us":
        drupal_set_title(t("Edit Contact Us"));
        break;
      case "life_of_musashi":
        drupal_set_title(t("Edit Life of Musashi"));
        break;

    }
  }

  //TODO: Disabled for now
  //$mobile = mobile_tools_is_mobile_device();
  if (isset($mobile['type']) && $mobile['type'] == "mobile") {
    //top image - mobile
    $button_fid = variable_get('wc_top_mobile_image_fid', '');
    $map_fid = variable_get('wc_top_map_mobile_image_fid', '');

    if(!empty($button_fid) && !empty($map_fid)) {
      $button_file = file_load($button_fid);
      $map_file = file_load($map_fid);
      if($button_file && $map_file) {
        $vars['top_image_file'] = file_create_url($button_file->uri);
        $vars['top_image_link'] = file_create_url($map_file->uri);
      }
    }
  } else {
    //top image - desctop
    $image_fid = variable_get('wc_top_image_fid', '');
    $image_link_url = variable_get('wc_top_image_link', 'http://www.westernconceptsdining.com/westfest');
    if(!empty($image_fid) && !empty($image_link_url)) {
      $image_file = file_load($image_fid);
      if($image_file) {
        $vars['top_image_file'] = file_create_url($image_file->uri);
        $vars['top_image_link'] = $image_link_url;
      }
    }
  }

}

/**
 * Implements hook_admin_menu_output_alter().
 */
function wcmusashis_custom_admin_menu_output_alter(&$content) {
  if (!user_access('menu access admin index item')) {
    if (!empty($content['menu']['admin/index'])) {
      unset($content['menu']['admin/index']);
    }
  }
}


/**
 * Implements hook_theme().
 */
function wcmusashis_custom_theme() {
  $theme_path = drupal_get_path('module', 'wcmusashis_custom');
  return array(
    'wcmusashis_custom__gift_cards' => array(
      'variables' => array(
        'image' => NULL,
        'button' => NULL,
      ),
      'template' => 'wcmusashis-custom--gift_cards',
      'path' => $theme_path . '/templates',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function wcmusashis_custom_block_info() {
  $blocks = array();
  $blocks['wcmusashis_custom_cards_block'] = array(
    'info' => t('Gift cards popup'),
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function wcmusashis_custom_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'wcmusashis_custom_cards_block':
      $form['wcmusashis_custom_gift_cards_url'] = array(
        '#type' => 'textfield',
        '#title' => t('Shop url'),
        '#size' => 60,
        '#default_value' => variable_get('wcmusashis_custom_gift_cards_url', ''),
      );
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function wcmusashis_custom_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'wcmusashis_custom_cards_block':
      variable_set('wcmusashis_custom_gift_cards_url', $edit['wcmusashis_custom_gift_cards_url']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function wcmusashis_custom_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'wcmusashis_custom_cards_block':
      $block['subject'] = t('');
      $block['content'] = _wcmusashis_custom_gift_cards_block_content();
      break;
  }

  return $block;
}

/**
 * Gift cards popup block.
 *
 * @return null|string
 */
function _wcmusashis_custom_gift_cards_block_content() {
  $url = variable_get('wcmusashis_custom_gift_cards_url', '');
  $button = l('<span>' . t('SHOP NOW') . '</span>', $url, array(
    'attributes' => array('class' => array('btn'), 'target' => '_blank'),
    'html' => TRUE,
  ));
  $image_url = drupal_get_path('theme', 'wcmusashis') . '/images/tmp/popup-img.jpg';
  $image = theme('image', array('path' => $image_url));
  $output = theme("wcmusashis_custom__gift_cards", array(
    'image' => $image,
    'button' => $button
  ));
  return $output;
}

/**
 * Implements template_preprocess_block().
 */
function wcmusashis_custom_preprocess_block(&$vars) {

  switch ($vars['block']->delta) {
    case 'wcmusashis_custom_cards_block':
      $vars['classes_array'][] = 'b-popup active';
      break;
  }
}

/**
 * Implements hook_form_alter().
 */
function wcmusashis_custom_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case "bean_form":
      if(user_access('administrator')) {
        $form['revision']['#access'] = TRUE;
      }
      else{
        $form['revision']['#access'] = FALSE;
      }

      break;
  }
}

/**
 * Implements hook_js_alter().
 */
function wcmusashis_custom_js_alter(&$js) {
  //Optimize plugin into your existing Analytics tracking code
  if (!empty($js['sites/all/modules/contrib/google_analytics/googleanalytics.js'])) {
    $position = array_search('sites/all/modules/contrib/google_analytics/googleanalytics.js', array_keys($js));

    $optimize_plugin = $js['sites/all/modules/contrib/google_analytics/googleanalytics.js'];
    $optimize_plugin['type'] = 'inline';
    $optimize_plugin['data'] = "(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
      h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
      (a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c; })
      (window,document.documentElement,'async-hide','dataLayer',4000, {'GTM-NG36CX3':true});";

    $js = array_slice($js, 0, $position, true) +
      array("optimize_plugin" => $optimize_plugin) +
      array_slice($js, $position, count($js)-1, true);
  }
}