<div class="b-bot-nav b-nav collapsed wrapper-drop-down">
  <div class="btn-dd">
    <a href="#">Home</a>
  </div>
  <div class="nav-items box-drop-down">
    <ul class="menu">
      <li>
        <a href="#">Home</a>
      </li>
      <li>
        <a href="#">Contact us</a>
      </li>
      <li>
        <a href="#">RESERVATIONS</a>
      </li>
      <li>
        <a href="#">ABOUT US</a>
      </li>
      <li>
        <a href="#">MENU</a>
      </li>
      <li>
        <a href="#">GALLERY</a>
      </li>
      <li>
        <a href="#">REWARD CARD MEMBERS</a>
      </li>
      <li>
        <a href="#">PROGRESSIVE DINNER</a>
      </li>
    </ul>
  </div>
</div>