<nav class="nav b-nav-header-bottom clearfix">
	<div class="wrapper-nav">
		<ul class="menu">
			<li>
				<a class="item-home" href="#">Home</a>
			</li>
			<li>
				<a href="#">Menus</a>
			</li>
			<li class="active">
				<a href="#">Life of musashi</a>
			</li>
			<li>
				<a href="#">About us</a>
			</li>
			<li>
				<a href="#">Gallery</a>
			</li>
			<li>
				<a href="#">Store</a>
			</li>
			<li>
				<a href="#">Contact Us</a>
			</li>
		</ul>
	</div>
</nav>